# Generated by Django 3.1.2 on 2021-01-11 15:37

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks
import wagtail_pdf_view.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0059_apply_collection_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(default=datetime.datetime.now)),
                ('author', models.CharField(max_length=200)),
                ('content', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('text', wagtail.core.blocks.RichTextBlock())], blank=True)),
            ],
            bases=(wagtail_pdf_view.mixins.PdfModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HtmlAndPdfPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('attachment', models.BooleanField(default=False, help_text='Download the .pdf file instead of displaying it in the browser')),
                ('creation_date', models.DateField(default=datetime.datetime.now)),
                ('author', models.CharField(max_length=200)),
                ('address', models.TextField(blank=True)),
                ('content', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('text', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock())], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_pdf_view.mixins.PdfViewPageMixin, 'wagtailcore.page'),
        ),
        migrations.CreateModel(
            name='SimplePdfPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('creation_date', models.DateField(default=datetime.datetime.now)),
                ('author', models.CharField(max_length=200)),
                ('content', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('text', wagtail.core.blocks.RichTextBlock())], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_pdf_view.mixins.PdfViewPageMixin, 'wagtailcore.page'),
        ),
    ]
