# Generated by Django 3.2 on 2021-05-18 07:35

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='htmlandpdfpage',
            name='body',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
