# Generated by Django 3.2.3 on 2021-07-29 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('home', '0004_auto_20210729_1458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demomodel',
            options={'permissions': (('can_view_pdf_demomodel', 'can view the demo model pdf'),)},
        ),
    ]
