# Generated by Django 3.2.3 on 2021-07-31 10:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import uuid
import wagtail_pdf_view.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoice', '0002_auto_20210731_1033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(default=0, editable=False, unique=True)),
                ('creation_date', models.DateField(default=datetime.datetime.now)),
                ('address', models.TextField(max_length=500)),
                ('due_by_date', models.DateField()),
                ('account_number', models.CharField(max_length=24)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_pdf_view.mixins.PdfModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('quantity', models.IntegerField()),
                ('invoice', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoice.invoice')),
            ],
        ),
    ]
