# Generated by Django 3.2.3 on 2021-07-28 14:26

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields
import wagtail_pdf_view.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('content', wagtail.core.fields.StreamField([('heading', wagtail.core.blocks.CharBlock(form_classname='full title')), ('text', wagtail.core.blocks.RichTextBlock())], blank=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(wagtail_pdf_view.mixins.PdfViewPageMixin, 'wagtailcore.page'),
        ),
    ]
