# Generated by Django 4.0 on 2024-10-03 13:25

from django.db import migrations
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210728_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportpage',
            name='content',
            field=wagtail.fields.StreamField([('chapter', wagtail.blocks.CharBlock(form_classname='full title')), ('columns', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('sub_heading', wagtail.blocks.CharBlock(required=False)), ('text', wagtail.blocks.RichTextBlock())])), ('competences', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('sub_heading', wagtail.blocks.CharBlock(required=False)), ('entries', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.CharBlock()), ('kind', wagtail.blocks.ChoiceBlock(choices=[('table-content', 'Table content'), ('heading', 'Heading titles'), ('multi-columns', 'Multi-column text'), ('internal-links', 'Internal links'), ('style', 'Page style')]))], label='Entry')))])), ('offers', wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock(form_classname='full title')), ('sub_heading', wagtail.blocks.CharBlock(required=False)), ('entries', wagtail.blocks.ListBlock(wagtail.blocks.StructBlock([('heading', wagtail.blocks.CharBlock()), ('text', wagtail.blocks.CharBlock()), ('price', wagtail.blocks.IntegerBlock()), ('items', wagtail.blocks.ListBlock(wagtail.blocks.CharBlock()))], label='Entry')))]))], blank=True, use_json_field=True),
        ),
    ]
